version: 2.1
jobs:
  unit-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        user: root
    steps:
      - checkout
      - run:
          name: Run unit tests
          working_directory: ~/project/backend/tests/UnitTests
          command: dotnet test

  integration-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        user: root
    steps:
      - checkout
      - run:
          name: Run unit tests
          working_directory: ~/project/backend/tests/IntegrationTests
          command: dotnet test

  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        user: root
    steps:
      - checkout
      - run:
          name: Run unit tests
          working_directory: ~/project/backend/scrum-poker-server
          command: dotnet build

workflows:
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - unit-test:
          filters:
            branches:
              only: master
          requires:
            - build
      - integration-test:
          filters:
            branches:
              only: master
          requires:
            - build
