version: 2.1
jobs:

  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        user: root
    steps:
      - checkout
      - run:
          name: Build
          working_directory: ~/project/backend/scrum-poker-server
          command: dotnet build

  unit-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        user: root
    steps:
      - checkout
      - run:
          name: Run unit tests
          working_directory: ~/project/backend/tests/UnitTests
          command: dotnet test

  integration-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        user: root
    steps:
      - checkout
      - run:
          name: Run integration tests
          working_directory: ~/project/backend/tests/IntegrationTests
          command: dotnet test

  load-test:
    docker:
      - image: locustio/locust:2.9.0
        user: root
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: 
          name: Setup env variables for load testing
          command: cat bash.env >> $BASH_ENV
      - run:
          name: Run load tests using Python Locust
          working_directory: ~/project/backend/tests/LoadTests
          command: locust

  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
            alb_url=$(terraform output alb_url)
            echo "export alb_url=$alb_url" >> $BASH_ENV
            cp $BASH_ENV bash.env
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve tfdestroy


workflows:
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - unit-test:
          requires:
            - build
      - integration-test:
          requires:
            - build
      - plan-apply:
          requires:
            - unit-test
            - integration-test
      - apply:
          requires:
            - plan-apply
      - load-test:
          requires:
            - apply
      - plan-destroy:
          requires:
            - apply
            - load-test
      - destroy:
          requires:
            - plan-destroy
