version: 2.1
jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        user: root
    steps:
      - checkout
      - run:
          name: List directory
          working_directory: ~/project/backend/tests/UnitTests
          command: ls
      - run:
          name: Run unit tests
          working_directory: ~/project/backend/tests/UnitTests
          command: dotnet test

workflows:
  sample:
    jobs:
      - build-and-test
