version: 2.1
jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        user: root
    steps:
      - checkout
      - run:
          name: Run unit tests
          working_directory: ~/project/backend/tests/UnitTests
          command: dotnet test
      - run:
          name: Build
          working_directory: ~/project/backend/scrum-poker-server
          command: dotnet build

workflows:
  sample:
    jobs:
      - build-and-test
